version: '3'
services:
        redis:
                image: redis
                container_name: orariotreni_redis
                volumes:
                        - ./redis-data:/data


        bot:
                build: .
                container_name: orariotreni_bot
                links:
                        - redis
